/*
 * This source file was generated by the Gradle 'init' task
 */
package project3.keeptheheap;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner; 

public class Main {
    public static void main(String[] args) throws FileNotFoundException {
        String fileName = "app/src/main/resources/data_sorted.txt";
        String outputFile = "app/src/main/resources/output.txt";

        MaxHeap<Integer> sequential = new MaxHeap<>();  
        Integer[] data = fileToArray(fileName);

        // build heap using sequential
        for (int i = 0; i < data.length; i++) {
            sequential.add(data[i]);
        }

        try {
            FileWriter write = new FileWriter(outputFile);
            write.write("Heap built using sequential insertions: ");
            sequential.printHeap10(write);
            write.write("Number of swaps in the heap creation: " + sequential.getCount());

            write.write("\nHeap after 10 removals: ");
            for (int i = 0; i < 10; i++) {
                sequential.removeMax();
            }
            sequential.printHeap10(write);
            write.write("\n");

            MaxHeap<Integer> optimal = new MaxHeap<>(data);
            write.write("Heap built using optimal method: ");
            optimal.printHeap10(write);
            write.write("Number of swaps in the heap creation: " + optimal.getCount());

            for (int i = 0; i < 10; i++) {
                optimal.removeMax();
            }
            write.write("\nHeap after 10 removals: ");
            optimal.printHeap10(write);

            write.close();
        } catch (IOException e) {
            System.out.println("An error occurred while writing to the file.");
            e.printStackTrace();
        }
    }

    static Integer[] fileToArray(String fileName) throws FileNotFoundException {
        Scanner sc = new Scanner(new File(fileName));
        int index = 0;
        Integer[] fileArray = new Integer[100];
        while (sc.hasNext()) {
            fileArray[index] = sc.nextInt();
            index++;
        }
        sc.close();
        return fileArray;
    }
}
