/*
 * This source file was generated by the Gradle 'init' task
 */
package project3.keeptheheap;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) throws FileNotFoundException {
        String fileName = "app/src/main/resources/data_sorted.txt";
        MaxHeap<Integer> sequential = new MaxHeap<>();  
        Integer[] data = fileToArray(fileName);

        // build heap using sequential
        for (int i = 0; i < data.length; i++) {
            sequential.add(data[i]);
        }

        System.out.print("Heap built using sequential insertions: ");
        sequential.printHeap10();
        System.out.println("Number of swaps in the heap creation: " + sequential.getCount());

        System.out.print("Heap after 10 removals: ");
        sequential.printHeap10();


        System.out.println("\n\n");

        // build heap using optimal method
        MaxHeap<Integer> optimal = new MaxHeap<>(data);

        // sort heap
        optimal.heapsort(optimal.getSize());

        System.out.print("Heap built using optimal method: ");
        optimal.printHeap10();
        System.out.println("Number of swaps in the heap creation: " + optimal.getCount());

        for (int i = 0; i < 10; i++) {
            optimal.removeMax();
        }
        System.out.print("Heap after 10 removals: ");
        optimal.printHeap10();
    }

    static Integer[] fileToArray(String fileName) throws FileNotFoundException {
        Scanner sc = new Scanner(new File(fileName));
        int index = 0;
        Integer[] fileArray = new Integer[100];
        while (sc.hasNext()) {
            fileArray[index] = sc.nextInt();
            index++;
        }
        sc.close();
        return fileArray;
    }
}
